### PR TITLE
Add supports feature checks to ContainerTemplate#instantiate

### PR DESCRIPTION
**Pull request by agrare**
Add checks for supported features to Container Templates

Depends on: https://github.com/ManageIQ/manageiq/pull/20314

### CODE REVIEW

**Comment by cben** [comment]
Is this temporary, or a limitation of 4.x?  AFAIK Templates still exist: https://docs.openshift.com/container-platform/4.4/openshift_images/using-templates.html

**Comment by cben** [comment]
approach LGTM :+1: but see Travis ``undefined method `supports'``

**Comment by agrare** [comment]
Yeah https://github.com/ManageIQ/manageiq/pull/20314 has to be merged first, `ContainerTemplate` never included `SupportsFeatureMixin` before

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit a241d31292bb970d184b85435aaa9083c268208d
Author: Oleg Barenboim <chessbyte@gmail.com>
Date:   Mon Jun 29 09:55:50 2020 -0400

    Merge pull request #185 from agrare/disable_container_template_instantiate_v4

    Add supports feature checks to ContainerTemplate#instantiate

    (cherry picked from commit ce5378f294c9d27f61bf51ef9489150a8444b368)
```

**Pull request merged**
