### PR TITLE
Add annotations to custom attributes on summary pages for routes and templates

### PR DESCRIPTION
**Pull request by liu-samuel**
Relevant PRs:
Providers-Kubernetes: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/530
UI-Classic: https://github.com/ManageIQ/manageiq-ui-classic/pull/9214
Core ManageIQ: https://github.com/ManageIQ/manageiq/pull/23074

Cross-Repo Tests:
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/879 
All passing except for known failing test cases in core ManageIQ

### CODE REVIEW

**Comment by Fryguy** [comment]
Should this be pushed down to the kubernetes layer?  Or is this a specific feature of OpenShift?

**Comment by Fryguy** [comment]
Additionally, I'm not sure smashing together annotations and attributes makes sense, but I like the idea of at least putting them under a separate key.

Annotations are pure metadata whereas labels have a functional usage in kubernetes (that is, they are the other half of selectors).

So, my original thought was separate modeling, even though technically they are just more key/value pairs at the raw data level.  @agrare Would like your thoughts here.

**Comment by agrare** [comment]
> Should this be pushed down to the kubernetes layer? Or is this a specific feature of OpenShift?

Routes and ContainerTemplates don't exist in kubernetes so that's why these parsers are here in the Openshift Parser Subclass

**Comment by agrare** [comment]
> Additionally, I'm not sure smashing together annotations and attributes makes sense, but I like the idea of at least putting them under a separate key.

Labels / Selectors / AdditionalAttributes are all CustomAttributes with a different "section", see https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/530/files#r1657929376

So I don't think this is "smashing" together annotations and attributes since they are kept separate unless I'm missing something.

**Comment by Fryguy** [comment]
Ohh I see - I thought labels were just top level, but if they are all sectioned out, then this is great.

**Comment by agrare** [comment]
Yeah I did a double-take when I saw `custom_attributes(container_group, :labels => labels, :node_selectors => node_selector_parts, :annotations => annotations)` in the kubernetes PR and had to see what the custom_attributes method did.

It might be better if custom_attributes took a section argument instead of one big hash that is splits up internally but that could be a nice follow-up after these changes.

**Review by agrare — APPROVED** [review]

**Pull request merged**
