### PR TITLE
Add OSP4/CRC support with API groups

### PR DESCRIPTION
**Pull request by agrare**
This adds support for OpenShift versions after removal of the `/oapi` endpoint in favor of using the `/apis/...` API groups.

If the `/oapi` endpoint is used we will continue to use it, otherwise we try to use the API groups present in OpenShift 4 and CodeReady Containers.

TODO:
- [x] Update the class level [`openshift_connect`](https://github.com/ManageIQ/manageiq-providers-openshift/blob/c575750278e8d3fef6e37dcc7de8212085833ecb/app/models/manageiq/providers/openshift/container_manager_mixin.rb#L34-L37) method to detect version
- [x] Update the instance level [`connect_client`](https://github.com/ManageIQ/manageiq-providers-openshift/blob/c575750278e8d3fef6e37dcc7de8212085833ecb/app/models/manageiq/providers/openshift/container_manager_mixin.rb#L40-L52) method to detect version
- [x] Add V4/CRC test scripts similar to [`test_objects_record.rb`](https://github.com/ManageIQ/manageiq-providers-openshift/blob/c575750278e8d3fef6e37dcc7de8212085833ecb/spec/vcr_cassettes/manageiq/providers/openshift/container_manager/test_objects_record.sh)
- [x] Add vcrs and specs for V4/CRC

Related: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/365 (might want to move this mixin to this repo but can be a follow-up)

https://github.com/ManageIQ/manageiq-providers-openshift/issues/139

### CODE REVIEW

**Comment by cben** [comment]
Yay.  Ref https://github.com/ManageIQ/manageiq-providers-openshift/issues/139

**Comment by cben** [comment]
This means minimal supported version will be 3.6.
I guess that's fine.

**Comment by agrare** [comment]
@cben I think this should still support everything we currently have, it only tries to use openshift 4 if `/oapi` doesn't exist

**Comment by agrare** [comment]
Ah thanks I forgot about that issue! I'll link in the commit and PR description

**Comment by cben** [comment]
Ah, right write before looking at code

**Comment by agrare** [comment]
Okay got this passing specs with v3 and v4 cassettes with just different total counts

**Comment by simaishi** [comment]
Backport conflicts on `app/models/manageiq/providers/openshift/inventory/collector/container_manager.rb`. There are a few PRs touching this file and some PRs have dependencies in kubernetes repo as well.  Some are marked as `jansa/yes?` and others have no jansa label.

@agrare not sure exactly which PRs need to be backported... Please let me know.

**Comment by agrare** [comment]
@simaishi yeah that's from trying to backport this without the legacy refresh cleanup that was also done but targeted for Kasparov not Jansa (https://github.com/ManageIQ/manageiq/issues/19888)

I've put in https://github.com/ManageIQ/manageiq-providers-openshift/pull/166 and https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/367 to backport just the OSP4 work and refactorings that it depended on

**Comment by simaishi** [comment]
Backported to jansa via https://github.com/ManageIQ/manageiq-providers-openshift/pull/166

**Pull request merged**
