### PR TITLE
Tag mapping in graph refresh

### PR DESCRIPTION
**Pull request by cben**
Covers routes, builds.

Images & templates tag mapping out of scope, they've never worked in old refresh either, will fix separately.

Depends on:
- [x] https://github.com/ManageIQ/manageiq/pull/16453 for specs
- [x]  ManageIQ/manageiq#16499 for fixing that spec
- [x]  (ManageIQ/manageiq#16501 OR revival of reverted ManageIQ/manageiq#16449)
  to define Tag.controlled_by_mapping scope
- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/162

Overview/plan issue: https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/126

@miq-bot add-label enhancement, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1470021

### CODE REVIEW

**Comment by cben** [comment]
missed ContainerBuild, adding...

**Comment by bazulay** [comment]
@moolitayer PTAL

**Comment by moolitayer** [comment]
@cben how is it possible that we didn't have `except` or deletion of these keys from the hash passed to save_inventory and no problems during persistence?

**Comment by cben** [comment]
Good question, don't know :)  checking...

**Comment by cben** [comment]
Found:
- routes & builds were blacklisted in inventory_collections.rb (k8s repo).  Now unecessary, PR soon, this PR should be merged first.
- images are still not mapped in parser, so no :tags key.  Will fix separately because also affects old refresh & backportable, and because I'm working on new vcr.  Prefer to keep the image changes I did in this PR, if you don't object

**Comment by cben** [comment]
OK, I'm working on fixing images & templates, will confirm soon how they interact with this PR.

**Comment by cben** [comment]
bah, images will be ugly because they go through data_index and need PRs to both repos.
@bazulay says that may wait for later, not blocker for current release.  Opening separate BZ for that.

=> dropped the `initialize_taggings_collection` line for images from this PR. 
Now it only covers routes & builds (and ManageIQ/manageiq-providers-kubernetes#180 matches this).
Can we get them merged (this first)?

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 5d3ad21dcf0319faf7fe68021241657b4e8e6a72
Author: Mooli Tayer <mtayer@redhat.com>
Date:   Mon Dec 4 11:34:27 2017 +0200

    Merge pull request #64 from cben/tag-mapper-InventoryCollection
    
    Tag mapping in graph refresh
    (cherry picked from commit bf456cf4ef888af873ad988631e725ff6acd3377)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1520488
```

**Pull request merged**
