### PR TITLE
Add ems_refresh.openshift.store_unused_images setting

### PR DESCRIPTION
**Pull request by cben**
openshift part of https://github.com/ManageIQ/manageiq/pull/14662 after repo split.  
**Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/11**

Strawman alternative/baseline for https://github.com/ManageIQ/manageiq/pull/14628.
Will allow to still get_container_images=true, but instead of saving metadata (labels etc) on all images openshift gave us, save it only for images that have been mentioned by pods.

cc @agrare @enoodle @zeari 
Added tests.  Recommend reviewing by commits (refactoring / new tests).

### CODE REVIEW

**Comment by cben** [comment]
@enoodle @zeari @simon3z Please review.

**Comment by simon3z** [comment]
@cben can you check travis?

**Comment by cben** [comment]
Travis should pass after https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/11 lands.

**Comment by cben** [comment]
rebased.  weird, now only hakiri & codeclimate run,  travis didn't — close-cycling to have it properly fail :)

**Comment by cben** [comment]
Closing per https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/11, can be revived if we decide to.

**Comment by cben** [comment]
@enoodle @moolitayer @Ladas @agrare Please review (recommend by commits).

Graph refresh test fails on child objects (labels etc) getting deleted when this causes an image to be archived.  Might affect other scenarios, will investigate and open issue/BZ, for now only need this option in save_inventory mode (the customer that needs this runs euwe).

**Comment by simon3z** [comment]
@agrare @moolitayer can anyone review/approve? Thanks!

**Comment by agrare** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1486483

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/15917

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq/pull/15907

**Pull request merged**
