### PR TITLE
Switch to proper targeted refresh

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:
- [x] https://github.com/ManageIQ/manageiq/pull/17846
- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/272

Switch to proper targeted refresh

### CODE REVIEW

**Comment by Ladas** [comment]
Hm specs are not working yet properly (if I change also k8s repo)

**Comment by Ladas** [comment]
@agrare @gtanzillo ok, so the specs were not passing because all the queries were wrong and we actually need the k8s code for the config to take place

**Comment by cben** [comment]
I assumed gaprindashvili/no, correct the labels if I'm wrong...

The specs are green here, _before_ I merged the k8s PR:
https://travis-ci.org/ManageIQ/manageiq-providers-openshift/builds/414850121
Does this mean we're lacking coverage?

Close-cycling to rerun specs with k8s changes.

**Comment by Ladas** [comment]
@cben right, I think the specs were green because the k8s was overwriting the shared_options, so removing it here and just having the methods had no effect.

Locally it was failing when k8s shared_options were removed.

**Pull request merged**
