### PR TITLE
run provider generator to sync changes from core

### PR DESCRIPTION
**Pull request by durandom**
ran the generator again with

```bash
bundle exec rails g provider <name> --path ../
```

these are the changes.

### CODE REVIEW

**Comment by moolitayer** [comment]
@durandom what changes do we expect to see as a result of these changes?

**Comment by durandom** [comment]
all will continue to work as usual.
this is just refactoring.

the spec_helper will now also look for local shared spec, in case you need some

**Comment by moolitayer** [comment]
@cben please review

**Comment by cben** [comment]
LGTM :+1:

Side question: do you know if/how we can share spec helpers between kubernetes and openshift provider repos?

**Pull request merged**
