### PR TITLE
Add openshift monitoring manager

### PR DESCRIPTION
**Pull request by moolitayer**
This is the third item of ManageIQ/manageiq-providers-kubernetes#39

Depends on: ManageIQ/manageiq#15354

### CODE REVIEW

**Comment by moolitayer** [comment]
@simon3z @blomquisg @Ladas please take a look

**Comment by Ladas** [comment]
looks great, just fix the rubocop issues please

**Comment by moolitayer** [comment]
Thanks @Ladas I'll probably have a few more changes to this PR once I finish the event collection that uses the new managers.

**Comment by moolitayer** [comment]
@durandom @Ladas @cben please review
(we have to merge relatively fast, https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/38 will break manageiq/manageiq and we have to merge this one and part of  https://github.com/ManageIQ/manageiq/pull/15506 to fix that)

**Pull request merged**
