### PR TITLE
Fix parsing for Container Template without objects

### PR DESCRIPTION
**Pull request by zakiva**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1461785

Openshift issue: https://github.com/openshift/origin/issues/14730

### CODE REVIEW

**Comment by zakiva** [comment]
@miq-bot add_label bug, fine/yes

**Comment by zakiva** [comment]
@simon3z @moolitayer  Please review

As @cben mentioned in the BZ, the objects array doesn't have `omitempty` according to https://github.com/openshift/origin/blob/master/pkg/template/api/v1/types.go#L31 so maybe this is worth mentioning as an issue in the openshift API, otherwise checking whether a field has `omitempty` or not is meaningless for us in the parser context.

**Comment by cben** [comment]
LGTM.  Have you checked in real life?  My BZ steps to reproduce are based on user report but I didn't try them.

**Comment by zakiva** [comment]
> LGTM. Have you checked in real life? My BZ steps to reproduce are based on user report but I didn't try them.

Checked of course :)

**Comment by moolitayer** [comment]
@zakiva Please ping me after you 
- open an issue on OpenShift 
- and add a link to it in the PR description

Thanks!

**Comment by zakiva** [comment]
> @zakiva Please ping me after you
> 
> open an issue on OpenShift
> and add a link to it in the PR description
> Thanks!

@moolitayer done, anyway I believe we should merge it on our side regardless their response as it fails the refresh.

**Comment by moolitayer** [comment]
> @moolitayer done, anyway I believe we should merge it on our side regardless their response as it fails the refresh.

of course

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit d225fa0003a7f5b77d048f634290de796d37c195
Author: Mooli Tayer <mtayer@redhat.com>
Date:   Mon Jun 19 13:01:50 2017 +0300

    Merge pull request #24 from zakiva/fix_nil_objects
    
    Fix parsing for Container Template without objects
    (cherry picked from commit 7ff46d374a68156d4a27c2531e7db5bce503c53b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1462801
```

**Pull request merged**
