### PR TITLE
removing openscap_result factories and updating tests

### PR DESCRIPTION
**Pull request by enoodle**
This is removing the `openscap_result` factories to move them to the core repository where they should be. 
This is coupled with https://github.com/ManageIQ/manageiq/pull/16762

Also simplifies the test that is using these factories as it can now avoid the `create_rule_results` callback.

### CODE REVIEW

**Comment by moolitayer** [comment]
@enoodle I'm not sure about removing the callback, maybe you can explain.

The existing test would use the OpenSCAP binary (when it is available) and parse an actual arf file with it.
Are we removing that? Do we have it done somewhere else?

**Comment by enoodle** [comment]
@moolitayer I feel like this should be tested on the main repo in the spec for the `OpenscapResult` and not here. https://github.com/ManageIQ/manageiq/blob/master/spec/models/openscap_result_spec.rb
This test is not using this file and is removing the rule results generated from it for other rule results that are convenient to work with.

**Comment by moolitayer** [comment]
@enoodle Not sure I understand, do you want to move the SCAP test to the main repo?

**Comment by enoodle** [comment]
@moolitayer Yes, it shouldn't be here. This test was not suppose to test `OpenscapResult` anyway, but the functionality of `Openshift::ContainerImage` so it doesn't need the callback. Do you want to create a test that will read this Openscap report file in the main repo instead?

**Comment by moolitayer** [comment]
I don't want to pile other assignments on to you. Do you want to keep the callback out so we can merge sooner? (I remember what you originally needed is the factory moving to core)
I just reluctant to get rid of the test since we have that already.

**Comment by enoodle** [comment]
@moolitayer This is the same file that is returned in the kubernetes repo test for the scanning job [1]
There on the test "completes successfully" it is using this file to create an OpenscapResult.

[1] https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb#L99

**Comment by moolitayer** [comment]
Ready for merge together with the core PR

**Comment by moolitayer** [comment]
When running this with #16762
```
Failures:

  1) ManageIQ::Providers::Openshift::ContainerManager::Refresher classical refresh will skip container_images if get_container_images = false
     Failure/Error: super(inventory, options)
     
     SupportsFeatureMixin::UnknownFeatureError:
       Feature ':reconfigure_disksize' is unknown to SupportsFeatureMixin.
```

```
rspec ./spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb[1:1:3] # ManageIQ::Providers::Openshift::ContainerManager::Refresher classical refresh will skip container_images if get_container_images = false
```

I'm not sure it is related to this PR, @enoodle can you get to the bottom of this?

**Comment by moolitayer** [comment]
@miq-bot add_label wip

**Comment by agrare** [comment]
With https://github.com/ManageIQ/manageiq/pull/16762 merged locally this passes spec tests

**Pull request merged**
